import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 Physical AI Textbook Sidebar Structure:
 - Organized by modules and weeks
 - Supports navigation by week (1-13), module (1-4), and topic
 - Nested categories with auto-collapse for better UX
 */
const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Introduction (Weeks 1-2)',
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'intro',
        },
      ],
    },
    {
      type: 'category',
      label: 'Foundational Setup',
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'setup',
        },
      ],
    },
    {
      type: 'category',
      label: 'Module 1: ROS 2 Fundamentals (Weeks 1-3)',
      collapsed: false,
      items: [
        'module-1/ros2-fundamentals',
        {
          type: 'autogenerated',
          dirName: 'module-1-ros2',
        },
      ],
    },
    {
      type: 'category',
      label: 'Module 2: Digital Twin & Sensors (Weeks 4-6)',
      collapsed: true,
      items: [
        'module-2/digital-twins',
        'module-2/sensor-integration',
        {
          type: 'autogenerated',
          dirName: 'module-2-digital-twin',
        },
      ],
    },
    {
      type: 'category',
      label: 'Module 3: Isaac Sim & Planning (Weeks 7-9)',
      collapsed: true,
      items: [
        'module-3/nvidia-isaac-sim',
        'module-3/motion-planning',
        {
          type: 'autogenerated',
          dirName: 'module-3-isaac',
        },
      ],
    },
    {
      type: 'category',
      label: 'Module 4: VLA & Humanoids (Weeks 10-13)',
      collapsed: true,
      items: [
        'module-4/vla-models',
        'module-4/humanoid-robotics',
        {
          type: 'autogenerated',
          dirName: 'module-4-vla',
        },
      ],
    },
    {
      type: 'category',
      label: 'Capstone Project',
      collapsed: true,
      items: [
        {
          type: 'autogenerated',
          dirName: 'capstone',
        },
      ],
    },
    {
      type: 'category',
      label: 'Assessments',
      collapsed: true,
      items: [
        {
          type: 'autogenerated',
          dirName: 'assessments',
        },
      ],
    },
    {
      type: 'category',
      label: 'Reference',
      collapsed: true,
      items: [
        {
          type: 'autogenerated',
          dirName: 'reference',
        },
      ],
    },
    {
      type: 'category',
      label: 'For Instructors',
      collapsed: true,
      items: [
        {
          type: 'autogenerated',
          dirName: 'instructors',
        },
      ],
    },
  ],
};

export default sidebars;
